# .gitlab-ci.yml
pages:
  stage: deploy
  script:
    - mv index.html public
    - mv styles.css public
  artifacts:
    paths:
      - public
  only:
    - master # Adjust this if you want to deploy only on a specific branch